<?php
/** Phase C Corporate Services landing. Target route /corporate-services/; contact routing intentionally gated. */
if ( ! defined( 'ABSPATH' ) ) exit;

function bes_site_core_render_corporate_services() {
    $experiences=array(
        array('icon'=>'fa-solid fa-seedling','title'=>'Workplace Wellbeing','body'=>'Mendukung karyawan agar lebih sehat, bahagia, dan tangguh melalui pengalaman wellbeing yang holistik.'),
        array('icon'=>'fa-solid fa-person-praying','title'=>'Mindfulness & Meditation','body'=>'Meningkatkan fokus, keseimbangan emosi, dan kejernihan berpikir di tengah dinamika dunia kerja.'),
        array('icon'=>'fa-solid fa-person-walking','title'=>'Yoga & Mindful Movement','body'=>'Membantu mengurangi stres, meningkatkan kebugaran, dan menghadirkan energi yang lebih positif.'),
        array('icon'=>'fa-solid fa-music','title'=>'Sound Healing Experience','body'=>'Pengalaman relaksasi melalui terapi suara untuk membantu menenangkan sistem saraf dan memulihkan keseimbangan.'),
        array('icon'=>'fa-solid fa-people-group','title'=>'Team Connection','body'=>'Membangun hubungan yang lebih kuat melalui komunikasi, empati, dan kolaborasi yang bermakna.'),
        array('icon'=>'fa-solid fa-compass','title'=>'Leadership Reflection','body'=>'Memberikan ruang bagi para pemimpin untuk berhenti sejenak, berefleksi, dan mengambil keputusan dengan lebih sadar.'),
        array('icon'=>'fa-solid fa-star','title'=>'Customized Corporate Journey','body'=>'Setiap program dirancang khusus sesuai tujuan organisasi, dinamika tim, dan hasil yang ingin dicapai.'),
    );
    ob_start(); ?>
    <main class="font-body overflow-hidden">
        <section class="relative min-h-[85vh] flex items-end bg-bes-forest-deep overflow-hidden" aria-labelledby="bes-corp-heading"><div class="bes-fret absolute top-0 inset-x-0"></div><div class="relative max-w-[1440px] mx-auto w-full px-6 md:px-10 pt-32 pb-20 md:pb-28"><div class="max-w-3xl"><p class="bes-reveal text-[10px] uppercase tracking-nav font-bold text-bes-leaf mb-5">Corporate Services</p><h1 id="bes-corp-heading" class="bes-reveal font-display text-5xl md:text-6xl lg:text-7xl text-white leading-tight mb-6">Memberdayakan Individu.<br><em class="not-italic text-bes-leaf">Menguatkan Organisasi.</em></h1><p class="bes-reveal text-white/55 text-base md:text-lg leading-relaxed max-w-2xl mb-9">Di Bali Eling Spirit, kami bermitra dengan perusahaan untuk menghadirkan pengalaman wellbeing yang bermakna—mendukung perkembangan individu, mempererat hubungan antartim, dan membangun budaya kerja yang lebih sehat. Setiap Corporate Journey dirancang secara khusus sesuai tujuan, tantangan, dan kebutuhan organisasi Anda.</p><a href="#bes-corporate-experiences" class="bes-reveal inline-flex bg-bes-leaf text-bes-forest font-bold text-[11px] uppercase tracking-label px-8 py-4 rounded-xl">Rancang Corporate Journey Anda</a></div></div></section>
        <section class="bg-bes-parchment py-20 md:py-28"><div class="max-w-[1200px] mx-auto px-6 md:px-10 grid lg:grid-cols-2 gap-12 lg:gap-20"><div><h2 class="bes-reveal font-display text-4xl md:text-5xl text-bes-bark mb-6">Dunia Kerja Saat Ini Membutuhkan Lebih dari Sekadar Produktivitas</h2><p class="bes-reveal text-bes-bark-muted leading-relaxed">Ketika wellbeing terabaikan, tingkat stres meningkat, komunikasi menjadi kurang efektif, keterlibatan menurun, dan kolaborasi ikut terdampak. Lingkungan kerja yang sehat membantu setiap individu berkembang secara utuh.</p></div><div><h2 class="bes-reveal font-display text-4xl md:text-5xl text-bes-bark mb-6">Pendekatan Holistik untuk Wellbeing di Tempat Kerja</h2><p class="bes-reveal text-bes-bark-muted leading-relaxed">Corporate Services memadukan mindfulness, yoga, meditasi, sound healing, refleksi diri, dan aktivitas yang mempererat hubungan antartim untuk mendukung wellbeing fisik, mental, emosional, dan spiritual.</p></div></div></section>
        <section id="bes-corporate-experiences" class="bg-bes-forest py-20 md:py-28"><div class="max-w-[1440px] mx-auto px-6 md:px-10"><div class="mb-12"><h2 class="bes-reveal font-display text-4xl md:text-5xl text-white mb-4">Corporate Experiences</h2><p class="bes-reveal text-white/45 max-w-2xl">Setiap organisasi memiliki kebutuhan yang berbeda. Karena itu, setiap Corporate Journey dirancang secara khusus agar memberikan pengalaman yang paling relevan bagi tim Anda.</p></div><div class="grid md:grid-cols-2 lg:grid-cols-3 gap-5"><?php foreach($experiences as $e): ?><article class="bes-reveal rounded-2xl border border-white/[.06] bg-white/[.03] p-6"><span class="w-10 h-10 rounded-xl bg-bes-leaf/[.07] border border-bes-leaf/[.12] flex items-center justify-center mb-6"><i class="<?php echo esc_attr($e['icon']); ?> text-bes-leaf" aria-hidden="true"></i></span><h3 class="font-display text-2xl text-white mb-3"><?php echo esc_html($e['title']); ?></h3><p class="text-sm text-white/45 leading-relaxed"><?php echo esc_html($e['body']); ?></p></article><?php endforeach; ?></div></div></section>
        <section class="bg-bes-ivory py-20 md:py-28"><div class="max-w-[1200px] mx-auto px-6 md:px-10 grid lg:grid-cols-2 gap-12 lg:gap-20"><div><h2 class="bes-reveal font-display text-4xl md:text-5xl text-bes-bark mb-6">Mengapa Bermitra dengan Bali Eling Spirit?</h2><p class="bes-reveal text-bes-bark-muted leading-relaxed">Kami menghadirkan pengalaman yang bermakna untuk membantu membangun individu yang lebih sehat, hubungan kerja yang lebih kuat, dan budaya organisasi yang membuat setiap orang merasa dihargai, terhubung, dan berkembang bersama.</p></div><div><h2 class="bes-reveal font-display text-4xl md:text-5xl text-bes-bark mb-6">Dirancang Sesuai Kebutuhan Organisasi Anda</h2><p class="bes-reveal text-bes-bark-muted leading-relaxed">Setiap Corporate Journey diawali dengan percakapan untuk memahami tujuan, tantangan, dan harapan organisasi Anda. Dari sana, pengalaman dirancang selaras dengan budaya perusahaan, karakter tim, dan hasil yang ingin dicapai.</p></div></div></section>
        <section class="bg-bes-forest-deep py-16 md:py-24"><div class="max-w-3xl mx-auto px-6 text-center"><h2 class="bes-reveal font-display text-4xl text-white mb-4">Mari Rancang Pengalaman Bermakna untuk Tim Anda</h2><p class="bes-reveal text-white/45 mb-5">Tempat kerja yang hebat dimulai dari individu yang merasa didukung, dihargai, dan terinspirasi. Mari bersama merancang Corporate Journey yang membantu tim Anda bertumbuh bersama.</p><p class="bes-reveal text-[10px] uppercase tracking-label text-bes-leaf/60">Konsultasikan Kebutuhan Anda</p><!-- Contact destination intentionally not wired until an approved Corporate channel is confirmed. --></div></section>
    </main>
    <?php return ob_get_clean();
}
add_shortcode( 'bes_corporate_services', 'bes_site_core_render_corporate_services' );
