<?php
/** Phase C adapter for canonical [bes_eling_sanctuary_retreat]. */
if ( ! defined( 'ABSPATH' ) ) exit;
require_once __DIR__ . '/baseline/eling-sanctuary-retreat.php';

function bes_site_core_render_eling_sanctuary_retreat_phase_c() {
    $wa='https://wa.me/6281228888873';
    $packages=array(
        array('title'=>'2 Hari 1 Malam','desc'=>'Retreat singkat bagi Sahabat yang ingin beristirahat, memulihkan keseimbangan, dan kembali menemukan ketenangan.','schedule'=>'Selasa – Rabu','price'=>'IDR 2.989K++'),
        array('title'=>'3 Hari 2 Malam','desc'=>'Pengalaman retreat yang lebih mendalam dengan waktu lebih banyak untuk refleksi diri, healing, dan pembaruan energi.','schedule'=>'Selasa – Kamis','price'=>'IDR 3.989K++'),
    );
    ob_start(); ?>
    <main class="font-body overflow-hidden">
        <section class="relative min-h-[85vh] flex items-end overflow-hidden bg-bes-forest-deep" aria-labelledby="bes-esr-heading"><div class="bes-fret absolute top-0 inset-x-0"></div><div class="relative w-full max-w-[1440px] mx-auto px-6 md:px-10 pt-32 pb-20 md:pb-28"><nav class="bes-reveal mb-8"><a href="/sanctuary/" class="text-[10px] uppercase tracking-nav font-bold !text-white/30 hover:!text-bes-gold transition-colors">← Sanctuary</a></nav><div class="max-w-3xl"><p class="bes-reveal text-[10px] uppercase tracking-nav font-bold text-bes-gold mb-5">Eling Sanctuary Retreat</p><h1 id="bes-esr-heading" class="bes-reveal font-display text-5xl md:text-6xl lg:text-7xl text-white leading-tight mb-6">Ruang Hening untuk<br><em class="not-italic text-bes-gold">Kembali kepada Diri Sendiri</em></h1><p class="bes-reveal text-white/55 text-base md:text-lg leading-relaxed max-w-2xl mb-9">Jauh dari kesibukan dan rutinitas, hadirkan ruang bagi tubuh untuk beristirahat, pikiran menjadi lebih tenang, dan hati kembali terhubung dengan hal-hal yang benar-benar bermakna. Pilih perjalanan 2 Hari 1 Malam atau 3 Hari 2 Malam.</p><a href="#bes-retreat-packages" class="bes-reveal inline-flex bg-bes-gold text-bes-forest font-bold text-[11px] uppercase tracking-label px-8 py-4 rounded-xl">Mulai Perjalanan Retreat</a></div></div></section>
        <section class="bg-bes-parchment py-20 md:py-28"><div class="max-w-[1200px] mx-auto px-6 md:px-10 grid lg:grid-cols-2 gap-12 lg:gap-20"><div><h2 class="bes-reveal font-display text-4xl md:text-5xl text-bes-bark mb-6">Sahabat, Kapan Terakhir Kali Sahabat Benar-Benar Beristirahat?</h2><p class="bes-reveal text-bes-bark-muted leading-relaxed">Beristirahat adalah memberi ruang untuk melambat, bernapas lebih dalam, dan mendengarkan kembali suara hati yang mungkin telah lama terabaikan.</p></div><div><h2 class="bes-reveal font-display text-4xl md:text-5xl text-bes-bark mb-6">Retreat yang Dirancang untuk Memulihkan Diri</h2><p class="bes-reveal text-bes-bark-muted leading-relaxed">Setiap pengalaman dirancang dalam suasana yang tenang dan penuh perhatian, memadukan praktik mindfulness, refleksi diri, dan keramahan khas Bali. Lebih dari sekadar berlibur, ini adalah kesempatan untuk kembali mengenal diri sendiri.</p></div></div></section>
        <section id="bes-retreat-packages" class="bg-bes-forest py-20 md:py-28"><div class="max-w-5xl mx-auto px-6 md:px-10"><div class="text-center mb-12"><h2 class="bes-reveal font-display text-4xl md:text-5xl text-white mb-4">Pilih Perjalanan Retreat Sahabat</h2><p class="bes-reveal text-white/45">Pilih durasi perjalanan yang paling sesuai dengan waktu dan kebutuhan Sahabat.</p></div><div class="grid md:grid-cols-2 gap-6"><?php foreach($packages as $p): ?><article class="bes-reveal rounded-2xl border border-white/[.06] bg-white/[.03] p-7 md:p-9"><span class="text-[10px] uppercase tracking-label font-bold text-bes-gold">Eling Sanctuary Retreat</span><h3 class="font-display text-3xl text-white mt-3 mb-4"><?php echo esc_html($p['title']); ?></h3><p class="text-white/45 leading-relaxed mb-7"><?php echo esc_html($p['desc']); ?></p><dl class="space-y-3 mb-8"><div class="flex justify-between gap-5 border-b border-white/[.05] pb-3"><dt class="text-xs uppercase tracking-label text-white/25">Jadwal</dt><dd class="text-sm text-white/70"><?php echo esc_html($p['schedule']); ?></dd></div><div class="flex justify-between gap-5"><dt class="text-xs uppercase tracking-label text-white/25">Investasi</dt><dd class="text-sm text-white/70"><?php echo esc_html($p['price']); ?></dd></div></dl><a href="<?php echo esc_url($wa); ?>" target="_blank" rel="noopener noreferrer" class="inline-flex items-center gap-2 text-[10px] uppercase tracking-label font-bold text-bes-gold hover:!text-white transition-colors">Tanyakan Ketersediaan <i class="fa-solid fa-arrow-right"></i></a></article><?php endforeach; ?></div></div></section>
        <section class="bg-bes-ivory py-20 md:py-28"><div class="max-w-3xl mx-auto px-6 text-center"><h2 class="bes-reveal font-display text-4xl md:text-5xl text-bes-bark mb-6">Mengapa Memilih Eling Sanctuary Retreat?</h2><p class="bes-reveal text-bes-bark-muted leading-relaxed">Karena pemulihan yang sejati dimulai saat kita memberi izin pada diri sendiri untuk berhenti sejenak. Dalam suasana Bali Eling Spirit yang tenang dan penuh kehangatan, setiap retreat mengajak Sahabat kembali terhubung dengan alam, menemukan kejernihan, keseimbangan, dan kedamaian.</p></div></section>
        <section class="bg-bes-forest-deep py-16 md:py-24"><div class="max-w-3xl mx-auto px-6 text-center"><h2 class="bes-reveal font-display text-4xl text-white mb-4">Setiap Retreat Dimulai dari Sebuah Niat</h2><p class="bes-reveal text-white/45 mb-8">Saat Sahabat siap untuk berhenti sejenak, kami siap menyambut dengan sepenuh hati.</p><a href="<?php echo esc_url($wa); ?>" target="_blank" rel="noopener noreferrer" class="bes-reveal inline-flex bg-bes-gold text-bes-forest font-bold text-[11px] uppercase tracking-label px-8 py-4 rounded-xl">Mulai Perjalanan Retreat</a></div></section>
    </main>
    <?php return ob_get_clean();
}
remove_shortcode( 'bes_eling_sanctuary_retreat' );
add_shortcode( 'bes_eling_sanctuary_retreat', 'bes_site_core_render_eling_sanctuary_retreat_phase_c' );
