<?php
/** Phase C Healing & Therapy landing. Target route /healing-therapy/ (Phase F provisioning). */
if ( ! defined( 'ABSPATH' ) ) exit;
require_once __DIR__ . '/shared-modal.php';

function bes_site_core_render_healing_therapy() {
    $wa = 'https://wa.me/6281228888873'; // Preserve verified Sanctuary channel; do not normalize globally.
    $cards = array(
        array('id'=>'healing-retreat','title'=>'Healing Retreat','desc'=>'Perjalanan healing setengah hari melalui yoga, meditasi, ritual penyucian, dan sound healing.','icon'=>'fa-solid fa-water'),
        array('id'=>'sacred-morning','title'=>'Sacred Morning Awakening','desc'=>'Awali hari dengan gerakan penuh kesadaran, latihan pernapasan, dan meditasi.','icon'=>'fa-solid fa-sun'),
        array('id'=>'mother-earth','title'=>'Mother Earth Purifications','desc'=>'Ritual penyucian air suci khas Bali untuk membersihkan energi dan menyegarkan jiwa.','icon'=>'fa-solid fa-droplet'),
        array('id'=>'sound-awakening','title'=>'Eling Sound Awakening','desc'=>'Getaran penyembuhan melalui Tibetan singing bowls, gong, dan mantra suci.','icon'=>'fa-solid fa-music'),
    );
    ob_start(); ?>
    <main class="font-body overflow-hidden">
        <section class="relative min-h-[85vh] flex items-end overflow-hidden bg-bes-forest-deep" aria-labelledby="bes-healing-heading"><div class="absolute inset-0 opacity-[0.018] pointer-events-none" style="background-image:radial-gradient(rgba(255,255,255,.5) 1px,transparent 1px);background-size:24px 24px"></div><div class="bes-fret absolute top-0 inset-x-0"></div><div class="relative w-full max-w-[1440px] mx-auto px-6 md:px-10 pt-32 pb-20 md:pb-28"><div class="max-w-3xl"><p class="bes-reveal font-body font-bold text-[10px] uppercase tracking-nav text-bes-leaf mb-5">Healing &amp; Therapy</p><h1 id="bes-healing-heading" class="bes-reveal font-display font-medium text-white text-5xl md:text-6xl lg:text-7xl leading-tight mb-6">Setiap Perjalanan Pulang<br><em class="not-italic text-bes-leaf">Dimulai dari Kesadaran</em></h1><p class="bes-reveal font-body font-light text-white/55 text-base md:text-lg leading-relaxed max-w-2xl mb-10">Sahabat, mungkin kehidupan belakangan ini terasa begitu sibuk hingga perlahan Sahabat mulai kehilangan koneksi dengan diri sendiri. Di Bali Eling Spirit, kami percaya healing bukan tentang menjadi pribadi yang baru, melainkan mengingat kembali siapa diri Sahabat yang sesungguhnya.</p><a href="#bes-healing-journeys" class="bes-reveal inline-flex items-center gap-2.5 bg-bes-leaf text-bes-forest font-bold text-[11px] uppercase tracking-label px-8 py-4 rounded-2xl hover:bg-bes-leaf-hover transition-colors">Mulai Perjalanan Healing Sahabat</a></div></div></section>
        <section class="bg-bes-parchment py-20 md:py-28"><div class="max-w-[1200px] mx-auto px-6 md:px-10 grid lg:grid-cols-2 gap-12 lg:gap-20"><div><p class="bes-reveal text-[10px] uppercase tracking-nav font-bold text-bes-moss mb-4">Ruang untuk Berhenti</p><h2 class="bes-reveal font-display text-4xl md:text-5xl text-bes-bark mb-6">Sahabat, Apa yang Sedang Sahabat Rasakan?</h2><p class="bes-reveal text-bes-bark-muted leading-relaxed">Terkadang beban yang paling berat adalah beban yang tidak terlihat. Mungkin akhir-akhir ini Sahabat merasa lelah secara emosional, pikiran terasa penuh, atau hanya merindukan satu momen untuk benar-benar tenang.</p></div><div><p class="bes-reveal text-[10px] uppercase tracking-nav font-bold text-bes-moss mb-4">Pendekatan Kami</p><h2 class="bes-reveal font-display text-4xl md:text-5xl text-bes-bark mb-6">Jalan Pulang yang Lembut Menuju Diri Sendiri</h2><p class="bes-reveal text-bes-bark-muted leading-relaxed">Melalui yoga, meditasi, breathwork, ritual penyucian, sound healing, dan pendampingan personal, kami menghadirkan ruang yang aman agar proses healing dapat berlangsung secara alami, sesuai ritme Sahabat.</p></div></div></section>
        <section id="bes-healing-journeys" class="relative bg-bes-forest py-20 md:py-28"><div class="max-w-[1440px] mx-auto px-6 md:px-10"><div class="mb-12"><p class="bes-reveal text-[10px] uppercase tracking-nav font-bold text-bes-leaf mb-4">Healing Experiences</p><h2 class="bes-reveal font-display text-4xl md:text-5xl text-white mb-4">Temukan Perjalanan Healing Sahabat</h2><p class="bes-reveal text-white/45 max-w-2xl">Setiap orang memiliki cerita, kebutuhan, dan perjalanan yang berbeda. Pilih pengalaman yang paling sesuai dengan kebutuhan Sahabat saat ini.</p></div><div class="grid md:grid-cols-2 xl:grid-cols-5 gap-5">
            <?php foreach($cards as $card): ?><button type="button" data-bes-modal-open="<?php echo esc_attr($card['id']); ?>" class="bes-reveal group text-left rounded-2xl border border-white/[.06] bg-white/[.03] hover:border-bes-leaf/25 transition-all p-6 min-h-[280px] flex flex-col"><span class="w-11 h-11 rounded-xl bg-bes-leaf/[.07] border border-bes-leaf/[.12] flex items-center justify-center mb-8"><i class="<?php echo esc_attr($card['icon']); ?> text-bes-leaf" aria-hidden="true"></i></span><h3 class="font-display text-2xl text-white mb-3"><?php echo esc_html($card['title']); ?></h3><p class="text-sm text-white/45 leading-relaxed mb-6"><?php echo esc_html($card['desc']); ?></p><span class="mt-auto text-[10px] font-bold uppercase tracking-label text-bes-leaf">Lihat Detail <i class="fa-solid fa-arrow-right ml-1" aria-hidden="true"></i></span></button><?php endforeach; ?>
            <a href="/eling-guiding/" class="bes-reveal group rounded-2xl border border-bes-gold/20 bg-bes-gold/[.05] hover:border-bes-gold/40 transition-all p-6 min-h-[280px] flex flex-col"><span class="w-11 h-11 rounded-xl bg-bes-gold/[.08] border border-bes-gold/[.14] flex items-center justify-center mb-8"><i class="fa-solid fa-user text-bes-gold" aria-hidden="true"></i></span><h3 class="font-display text-2xl text-white mb-3">Personal Session dengan Yogi</h3><p class="text-sm text-white/45 leading-relaxed mb-6">Ruang personal untuk pendampingan healing yang lebih mendalam sesuai kebutuhan perjalanan Sahabat.</p><span class="mt-auto text-[10px] font-bold uppercase tracking-label text-bes-gold">Lihat Sesi Personal <i class="fa-solid fa-arrow-right ml-1" aria-hidden="true"></i></span></a>
        </div></div></section>
        <section class="bg-bes-ivory py-20 md:py-28"><div class="max-w-3xl mx-auto px-6 md:px-10 text-center"><h2 class="bes-reveal font-display text-4xl md:text-5xl text-bes-bark mb-6">Mengapa Healing Bersama Bali Eling Spirit?</h2><p class="bes-reveal text-bes-bark-muted leading-relaxed">Healing bukanlah tujuan akhir, melainkan sebuah perjalanan untuk kembali mengingat diri sejati. Kami memadukan tradisi Bali yang autentik, pendampingan yang berpengalaman, dan suasana sanctuary yang mendukung harmoni tubuh, pikiran, dan jiwa.</p></div></section>
        <section class="bg-bes-forest-deep py-16 md:py-24"><div class="max-w-3xl mx-auto px-6 text-center"><h2 class="bes-reveal font-display text-4xl text-white mb-4">Saat Sahabat Siap, Kami Akan Menemani.</h2><p class="bes-reveal text-white/45 mb-8">Setiap perjalanan dimulai dari satu langkah sederhana. Dan kami akan menyambut Sahabat dengan sepenuh hati.</p><a href="<?php echo esc_url($wa); ?>" target="_blank" rel="noopener noreferrer" class="bes-reveal inline-flex items-center gap-2 bg-bes-leaf text-bes-forest font-bold text-[11px] uppercase tracking-label px-8 py-4 rounded-xl hover:bg-bes-leaf-hover transition-colors"><i class="fa-brands fa-whatsapp"></i>Mulai Perjalanan Sahabat</a></div></section>
    </main>
    <?php
    $healing_body='<p>Di tengah kesibukan hidup, jiwa membutuhkan ruang untuk beristirahat. Healing Retreat adalah perjalanan setengah hari yang memadukan yoga, breathwork, meditasi, ritual penyucian air suci, dan sound healing untuk membantu melepaskan beban emosional serta kembali menemukan ketenangan batin.</p><p><strong>Highlight:</strong> refleksi dan penetapan niat, yoga yang lembut dan intuitif, ritual penyucian air suci, serta terapi sound healing.</p>';
    echo bes_site_core_sanctuary_render_modal('healing-retreat','Healing Retreat',$healing_body,array('Termasuk'=>'Sarapan, makan siang, dan layanan antar-jemput Sang Spa & Sang Tropical dengan reservasi terlebih dahulu.','Investasi'=>'IDR 1.559K++'),array('href'=>$wa,'label'=>'Mulai Perjalanan Ini','external'=>true));
    echo bes_site_core_sanctuary_render_modal('sacred-morning','Sacred Morning Awakening','<p>Mulailah pagi dengan breathwork, Bali Hatha Yoga, dan meditasi untuk menyambut hari dengan kejernihan, keseimbangan, serta semangat baru.</p>',array('Durasi'=>'120 Menit','Jadwal'=>'Setiap hari kecuali Senin · 08.00–10.00 WITA','Investasi'=>'IDR 379K'),array('href'=>$wa,'label'=>'Mulai Perjalanan Ini','external'=>true));
    echo bes_site_core_sanctuary_render_modal('mother-earth','Mother Earth Purifications','<p>Rasakan ritual penyucian air suci khas Bali di Pura Mengening. Dipandu melalui doa dan tradisi, perjalanan ini mengajak Sahabat melepaskan beban emosional, membersihkan energi, serta mengembalikan harmoni.</p>',array('Durasi'=>'120 Menit','Jadwal'=>'Setiap hari kecuali Senin · 10.00–12.00 WITA','Investasi'=>'IDR 699K'),array('href'=>$wa,'label'=>'Mulai Perjalanan Ini','external'=>true));
    echo bes_site_core_sanctuary_render_modal('sound-awakening','Eling Sound Awakening','<p>Nikmati pengalaman sound healing melalui Tibetan singing bowls, gong, dan mantra suci untuk membantu melepaskan ketegangan, menyeimbangkan energi, serta menghadirkan relaksasi mendalam.</p>',array('Durasi'=>'60 Menit','Jadwal'=>'Setiap hari kecuali Senin · 12.00–13.00 WITA','Investasi'=>'IDR 349K'),array('href'=>$wa,'label'=>'Mulai Perjalanan Ini','external'=>true));
    echo bes_site_core_sanctuary_modal_engine();
    return ob_get_clean();
}

add_shortcode( 'bes_healing_therapy', 'bes_site_core_render_healing_therapy' );
