<?php
/** Phase C Personal Session with Yogi landing. Existing related route /eling-guiding/ is reserved for Phase F reuse decision. */
if ( ! defined( 'ABSPATH' ) ) exit;
require_once __DIR__ . '/shared-modal.php';

function bes_site_core_render_personal_session_yogi() {
    $wa='https://wa.me/6287825899117'; // Preserve existing Eling Guiding route-specific channel exactly.
    $cards=array(
        array('id'=>'ruang-jiwa','title'=>'Ruang Jiwa','sub'=>'Spiritual Counseling','desc'=>'Ruang aman untuk berbagi, berefleksi, dan menemukan kejernihan bersama Yogi.'),
        array('id'=>'sound-chakra','title'=>'Sound Chakra Healing','sub'=>'','desc'=>'Terapi suara untuk membantu menyeimbangkan energi dan menghadirkan relaksasi yang mendalam.'),
        array('id'=>'crystal-chakra','title'=>'7 Chakra Crystal Healing','sub'=>'','desc'=>'Healing menggunakan kristal untuk membantu mengaktifkan dan menyeimbangkan tujuh chakra.'),
        array('id'=>'eling-therapy','title'=>'Eling Therapy','sub'=>'','desc'=>'Pendekatan healing yang lebih mendalam untuk membantu proses transformasi emosional dan spiritual.'),
    );
    ob_start(); ?>
    <main class="font-body overflow-hidden">
        <section class="relative min-h-[85vh] flex items-end bg-bes-forest-deep overflow-hidden" aria-labelledby="bes-personal-heading"><div class="bes-fret absolute top-0 inset-x-0"></div><div class="relative max-w-[1440px] mx-auto w-full px-6 md:px-10 pt-32 pb-20 md:pb-28"><div class="max-w-3xl"><p class="bes-reveal text-[10px] uppercase tracking-nav font-bold text-bes-gold mb-5">Personal Session dengan Yogi</p><h1 id="bes-personal-heading" class="bes-reveal font-display text-5xl md:text-6xl lg:text-7xl text-white leading-tight mb-6">Setiap Perjalanan Healing<br><em class="not-italic text-bes-gold">Bersifat Personal</em></h1><p class="bes-reveal text-white/55 text-base md:text-lg leading-relaxed max-w-2xl mb-9">Melalui sesi personal bersama Yogi, Sahabat akan mendapatkan pendampingan yang disesuaikan dengan kebutuhan emosional, mental, energi, maupun spiritual. Setiap sesi dilakukan dengan penuh perhatian, kehadiran, dan kearifan healing Bali yang autentik.</p><a href="#bes-personal-sessions" class="bes-reveal inline-flex items-center gap-2 bg-bes-gold text-bes-forest font-bold text-[11px] uppercase tracking-label px-8 py-4 rounded-xl hover:opacity-90 transition-opacity">Jadwalkan Sesi Personal</a></div></div></section>
        <section class="bg-bes-parchment py-20 md:py-28"><div class="max-w-[1200px] mx-auto px-6 md:px-10 grid lg:grid-cols-2 gap-12 lg:gap-20"><div><h2 class="bes-reveal font-display text-4xl md:text-5xl text-bes-bark mb-6">Apakah Perjalanan Ini untuk Sahabat?</h2><p class="bes-reveal text-bes-bark-muted leading-relaxed">Ada masa-masa ketika kita membutuhkan seseorang yang berjalan bersama. Sesi personal memberi ruang yang aman untuk mengeksplorasi perjalanan dengan ritme yang sesuai bagi diri sendiri.</p></div><div><h2 class="bes-reveal font-display text-4xl md:text-5xl text-bes-bark mb-6">Pendekatan yang Disesuaikan dengan Kebutuhan Sahabat</h2><p class="bes-reveal text-bes-bark-muted leading-relaxed">Tidak ada dua perjalanan healing yang benar-benar sama. Bersama Yogi, Sahabat akan menemukan pendekatan yang paling tepat untuk mendukung perjalanan menuju kejernihan, keseimbangan, dan kedamaian batin.</p></div></div></section>
        <section id="bes-personal-sessions" class="bg-bes-forest py-20 md:py-28"><div class="max-w-[1440px] mx-auto px-6 md:px-10"><div class="mb-12"><h2 class="bes-reveal font-display text-4xl md:text-5xl text-white mb-4">Pilih Sesi Healing Personal Sahabat</h2><p class="bes-reveal text-white/45 max-w-2xl">Setiap sesi menawarkan pendekatan yang berbeda sesuai kebutuhan perjalanan Sahabat.</p></div><div class="grid md:grid-cols-2 lg:grid-cols-4 gap-5"><?php foreach($cards as $card): ?><button type="button" data-bes-modal-open="<?php echo esc_attr($card['id']); ?>" class="bes-reveal text-left rounded-2xl border border-white/[.06] bg-white/[.03] hover:border-bes-gold/25 transition-colors p-6 min-h-[270px] flex flex-col"><span class="text-[10px] uppercase tracking-label font-bold text-bes-gold mb-6">Private Session</span><h3 class="font-display text-2xl text-white mb-1"><?php echo esc_html($card['title']); ?></h3><?php if($card['sub']): ?><p class="text-xs uppercase tracking-label text-white/30 mb-4"><?php echo esc_html($card['sub']); ?></p><?php endif; ?><p class="text-sm text-white/45 leading-relaxed mb-6"><?php echo esc_html($card['desc']); ?></p><span class="mt-auto text-[10px] uppercase tracking-label font-bold text-bes-gold">Lihat Detail</span></button><?php endforeach; ?></div></div></section>
        <section class="bg-bes-ivory py-20 md:py-28"><div class="max-w-4xl mx-auto px-6 md:px-10 text-center"><h2 class="bes-reveal font-display text-4xl md:text-5xl text-bes-bark mb-5">Kenali Pendamping Perjalanan Sahabat</h2><p class="bes-reveal text-bes-bark-muted leading-relaxed">Healing bukanlah perjalanan yang harus dilalui sendirian. Para Yogi kami hadir untuk menemani dengan penuh perhatian, ketulusan, dan tanpa menghakimi.</p><!-- Profile data intentionally omitted: approved source contains no verified profile dataset. --></div></section>
        <section class="bg-bes-parchment py-20 md:py-28"><div class="max-w-3xl mx-auto px-6 md:px-10 text-center"><h2 class="bes-reveal font-display text-4xl md:text-5xl text-bes-bark mb-5">Mengapa Memilih Sesi Personal?</h2><p class="bes-reveal text-bes-bark-muted leading-relaxed">Karena setiap perjalanan memiliki cerita yang berbeda. Melalui sesi personal, Sahabat mendapatkan ruang yang lebih mendalam untuk didengarkan, didampingi, dan menjalani proses healing sesuai kebutuhan diri sendiri.</p></div></section>
        <section class="bg-bes-forest-deep py-16 md:py-24"><div class="max-w-3xl mx-auto px-6 text-center"><h2 class="bes-reveal font-display text-4xl text-white mb-4">Setiap Perjalanan Dimulai dari Sebuah Percakapan</h2><p class="bes-reveal text-white/45 mb-8">Saat Sahabat siap, kami akan dengan hangat menyambut dan menemani perjalanan tersebut.</p><a href="<?php echo esc_url($wa); ?>" target="_blank" rel="noopener noreferrer" class="bes-reveal inline-flex items-center gap-2 bg-bes-gold text-bes-forest font-bold text-[11px] uppercase tracking-label px-8 py-4 rounded-xl"><i class="fa-brands fa-whatsapp"></i>Jadwalkan Sesi Personal</a></div></section>
    </main>
    <?php
    echo bes_site_core_sanctuary_render_modal('ruang-jiwa','Ruang Jiwa','<p>Ruang Jiwa adalah sesi konseling spiritual secara personal yang membantu Sahabat menemukan kembali ketenangan batin, memperoleh kejernihan, dan menghadapi tantangan hidup dengan kesadaran yang lebih utuh.</p>',array('Durasi'=>'60 Menit','Bersama'=>'Yogi Putra','Jadwal'=>'Kamis 10.00–17.00 · Jumat 14.00–16.00 · Sabtu 10.00–17.00','Investasi'=>'IDR 759K'),array('href'=>$wa,'label'=>'Jadwalkan Sesi','external'=>true));
    echo bes_site_core_sanctuary_render_modal('sound-chakra','Sound Chakra Healing','<p>Rasakan sesi healing melalui getaran crystal singing bowls, Tibetan bowls, chimes, dan vocal toning untuk membantu menyeimbangkan tujuh chakra dan menghadirkan relaksasi mendalam.</p>',array('Durasi'=>'60 Menit','Bersama'=>'Yogi Putra · Yogi Su','Jadwal'=>'Putra: Kamis 10.00–17.00, Jumat 14.00–16.00, Sabtu 10.00–17.00 · Su: Rabu 12.00–16.00, Jumat 10.00–17.00','Investasi'=>'IDR 879K'),array('href'=>$wa,'label'=>'Jadwalkan Sesi','external'=>true));
    echo bes_site_core_sanctuary_render_modal('crystal-chakra','7 Chakra Crystal Healing','<p>Healing menggunakan energi kristal untuk membantu menyeimbangkan tujuh chakra, melepaskan hambatan energi, serta mengembalikan kejernihan dan vitalitas tubuh.</p>',array('Durasi'=>'60 Menit','Bersama'=>'Yogi Putra · Yogi Su','Investasi'=>'IDR 649K'),array('href'=>$wa,'label'=>'Jadwalkan Sesi','external'=>true));
    echo bes_site_core_sanctuary_render_modal('eling-therapy','Eling Therapy','<p>Eling Therapy adalah sesi healing mendalam yang memadukan pendampingan spiritual, proses pembersihan batin, grounding, dan pelepasan emosi.</p><p><strong>Catatan penting:</strong> peserta diwajibkan telah mengikuti minimal satu Healing Retreat atau program retreat lain yang disertai sesi Spiritual Counseling sebelum mengikuti sesi ini.</p>',array('Durasi'=>'90 Menit','Bersama'=>'Yogi Putra','Reservasi'=>'Reservasi terlebih dahulu','Investasi'=>'IDR 1.759K'),array('href'=>$wa,'label'=>'Jadwalkan Sesi','external'=>true));
    echo bes_site_core_sanctuary_modal_engine();
    return ob_get_clean();
}

add_shortcode( 'bes_personal_session_yogi', 'bes_site_core_render_personal_session_yogi' );
