---
deployment:
  tasks:
    - export DEPLOYPATH=/home/markascl/bali-eling-spirit-v3/wp-content/plugins/bali-eling-spirit-site-core/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R plugin/bali-eling-spirit-site-core/. $DEPLOYPATH